# Generated by Django 5.0.2 on 2024-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='publishermodel',
            name='publisher',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmodel',
            unique_together={('title', 'author')},
        ),
    ]
